### ISSUE TITLE
Question about computing hard_positive_index 

### ISSUE THREAD

**Issue by Wuyxin** [Vanint/Core-tuning#1]
Hi,

There is a question I want to ask. I don't quite understand the operation in file `https://github.com/Vanint/Core-tuning/blob/main/Core-tuning.py`, line 190-line 195

```
hard_positive_index = positive_matrix.argmin(dim=1)
    for i in range(batch_size):  
        if hard_positive_index[i] == 0:
            hard_positive_index[i] = i 
```

I think here is trying to obtain the index of the hardest positive data. And you previous get `positive_matrix` via `positive_matrix = similarity_matrix * positive_mask`, which means Mij will be 1 if and only if i is not equal to j and yi=yj. But you take `argmin` here, which will give you the index with value of 0 but the smallest positive value. 

I use the below code instead. Pls point out if I missed sth. Thanks!
```
positive_matrix[positive_mask == 0] = 1e6
hard_positive_index = positive_matrix.argmin(dim=1)
```

**Comment by YifanZhang07** [comment]
Hi, to some degree, "positive_matrix[positive_mask == 0] = 1e6" can replace "positive_matrix = similarity_matrix * positive_mask".  This is for finding the most dissimilar positive pairs.

In addition, "(if hard_positive_index[i] == 0):  hard_positive_index[i] = i" is used to handle the case when no positive pairs exist in the current data batch.
