### ISSUE TITLE
Question about ImageNet20

### ISSUE THREAD

**Issue by PanHaulin** [Vanint/Core-tuning#2]
The ImageNet20 dataset I currently used comes from this tutorial：http://howto.untangle.ai/tutorials/imagenet_actlearn_tutorial/
But the fine-tuning on this dataset directly can only achieve 83% accuracy.
I think this dataset is not consistent with what is shown in the paper. 
Could you please share which classes are used in ImageNet20? Thanks!

**Comment by YifanZhang07** [comment]
Hi, as mentioned in Appendix C.2 of the paper, the ImageNet20 dataset is obtained by combining two open-source ImageNet subsets with 10 classes, i.e., ImaegNette and ImageWoof (Please refer to https://github.com/fastai/imagenette).

**Comment by YifanZhang07** [comment]
If any further question, we are glad to discuss
